import { ArrowRight, FlaskConical, PlusCircle, SearchCheck } from 'lucide-react';
import { useDashboard } from '../hooks/useDashboard';
import { LoadingState } from '../components/common/LoadingState';
import { formatDateTime } from '../utils/formatters';
import { SourceBadge } from '../components/common/SourceBadge';

export function DashboardPage({ onNavigate, onSelectReturn }: { onNavigate: (path: string) => void; onSelectReturn: (id: string) => void }) {
  const { data, loading } = useDashboard();
  if (loading) return <LoadingState message="Loading overview…"/>;
  const counts = data?.counts;
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">Activity overview</span><h1>ReturnGuard Overview</h1><p>A concise view of return activity across prepared and source-backed cases.</p></div></div><div className="overview-counts"><article><span>Total returns</span><strong>{counts?.total_returns ?? '—'}</strong></article><article><span>Controlled cases</span><strong>{counts?.controlled_returns ?? '—'}</strong></article><article><span>Source-backed</span><strong>{counts?.source_backed_returns ?? '—'}</strong></article></div><div className="shortcut-grid"><button onClick={() => onNavigate('/controlled-cases')}><FlaskConical/><span><strong>Explore controlled cases</strong><small>Prepared investigation scenarios</small></span><ArrowRight/></button><button onClick={() => onNavigate('/investigations')}><SearchCheck/><span><strong>Open investigations</strong><small>Review the active returns queue</small></span><ArrowRight/></button><button onClick={() => onNavigate('/raise-return')}><PlusCircle/><span><strong>Raise test return</strong><small>Simulate a source-backed request</small></span><ArrowRight/></button></div><section className="recent-panel"><div className="panel-heading"><div><span className="eyebrow">Latest activity</span><h2>Recent returns</h2></div><button className="rg-btn-secondary" onClick={() => onNavigate('/investigations')}>View investigations<ArrowRight size={15}/></button></div>{(data?.recent_returns || []).slice(0,5).map((item) => <button className="recent-row" key={item.return_id} onClick={() => onSelectReturn(item.return_id)}><span><strong>{item.return_id}</strong><small>{formatDateTime(item.assessment_at || item.requested_at)}</small></span><SourceBadge sourceType={item.source_type}/><span className="recent-product">{item.product.name}</span><span className="status-pill">{item.status}</span><ArrowRight size={16}/></button>)}</section></div>;
}
